Through this tadk we can understand how  different imputation methods influence data distribution and support
appropriate method selection during data preprocessing.Imputation is the act of assigning a convinient value to the whole data without changing the meaning of the data.The selection of imputation methods depend on the type of data, existence of outliers etc.

In [16]:
import pandas as pd
import numpy as np

In [17]:
# Creating the dataset
data = {
    'Age': [25, 30, np.nan, 45, 50, np.nan, 35],
    'Blood_Pressure': [120, 125, 130, np.nan, 140, 135, np.nan],
    'Cholesterol': [200, np.nan, 180, 220, np.nan, 210, 190],
    'Gender': ['Male', 'Female', np.nan, 'Female', 'Male', np.nan, 'Female']
}
df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

Original Dataset:

    Age  Blood_Pressure  Cholesterol  Gender
0  25.0           120.0        200.0    Male
1  30.0           125.0          NaN  Female
2   NaN           130.0        180.0     NaN
3  45.0             NaN        220.0  Female
4  50.0           140.0          NaN    Male
5   NaN           135.0        210.0     NaN
6  35.0             NaN        190.0  Female

In [18]:
#Inspect Dataset
#Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             5 non-null      float64
 1   Blood_Pressure  5 non-null      float64
 2   Cholesterol     5 non-null      float64
 3   Gender          5 non-null      object
dtypes: float64(3), object(1)
memory usage: 356.0+ bytes

The database contains the columns age,blood pressure ,cholesterol and gender. Gender contains categorical value while all teh other columns have numerical values.

In [19]:
#Summary Statistics
df.describe()

             Age  Blood_Pressure  Cholesterol
count   5.000000        5.000000     5.000000
mean   37.000000      130.000000   200.000000
std    10.368221        7.905694    15.811388
min    25.000000      120.000000   180.000000
25%    30.000000      125.000000   190.000000
50%    35.000000      130.000000   200.000000
75%    45.000000      135.000000   210.000000
max    50.000000      140.000000   220.000000

In [20]:
#missing values count
print(df.isnull().sum())

Age               2
Blood_Pressure    2
Cholesterol       2
Gender            2
dtype: int64

We use different imputations to replace the missing values present in the dataset.

In [21]:
#mean imputation
df_mean = df.copy()
numeric_cols = ['Age', 'Blood_Pressure', 'Cholesterol']
for col in numeric_cols:
    df_mean[col] = df_mean[col].fillna(df_mean[col].mean())
print("Dataset After Mean Imputation")
display(df_mean)

Dataset After Mean Imputation

    Age  Blood_Pressure  Cholesterol  Gender
0  25.0           120.0        200.0    Male
1  30.0           125.0        200.0  Female
2  37.0           130.0        180.0     NaN
3  45.0           130.0        220.0  Female
4  50.0           140.0        200.0    Male
5  37.0           135.0        210.0     NaN
6  35.0           130.0        190.0  Female

Using mean imputation we can replace the missing values with the arithemetic value of the column. It does not change the overall average and can help to reduce variance. But it can distort data if there is existence of outliers. It may weaken the relationship between variables and may not be suitable for highly skewed data.It is generally used for numerical data and is simple and fast.

In [22]:
df_mean.describe()

             Age  Blood_Pressure  Cholesterol
count   7.000000        7.000000     7.000000
mean   37.000000      130.000000   200.000000
std     8.465617        6.454972    12.909944
min    25.000000      120.000000   180.000000
25%    32.500000      127.500000   195.000000
50%    37.000000      130.000000   200.000000
75%    41.000000      132.500000   205.000000
max    50.000000      140.000000   220.000000

The missing vavlues in the numerical columns( age,blood pressure and cholestrol) are replaced with the mean value of the column)+.

In [23]:
#median imputation
df_median = df.copy()
for col in numeric_cols:
    df_median[col] = df_median[col].fillna(df_median[col].median())
print("Dataset After Median Imputation")
display(df_median)

Dataset After Median Imputation

    Age  Blood_Pressure  Cholesterol  Gender
0  25.0           120.0        200.0    Male
1  30.0           125.0        200.0  Female
2  35.0           130.0        180.0     NaN
3  45.0           130.0        220.0  Female
4  50.0           140.0        200.0    Male
5  35.0           135.0        210.0     NaN
6  35.0           130.0        190.0  Female

In median imputation the original values are sorted and the median is calculated which is later used to replace the missing values.It is an imputation method that is resistant to outliers and is better choice for skewed distributions. In comparison it preserves the central tendancy more acurately.

In [24]:
df_median.describe()

             Age  Blood_Pressure  Cholesterol
count   7.000000        7.000000     7.000000
mean   36.428571      130.000000   200.000000
std     8.521681        6.454972    12.909944
min    25.000000      120.000000   180.000000
25%    32.500000      127.500000   195.000000
50%    35.000000      130.000000   200.000000
75%    40.000000      132.500000   205.000000
max    50.000000      140.000000   220.000000

The missing vavlues in the numerical columns( age,blood pressure and cholestrol) are replaced with the median value of the column.

In [25]:
#mode imputation
df_mode = df.copy()
gender_mode = df_mode['Gender'].mode()[0]
df_mode['Gender'] = df_mode['Gender'].fillna(gender_mode)
print("Dataset After Mode Imputation")
display(df_mode)

Dataset After Mode Imputation

    Age  Blood_Pressure  Cholesterol  Gender
0  25.0           120.0        200.0    Male
1  30.0           125.0          NaN  Female
2   NaN           130.0        180.0  Female
3  45.0             NaN        220.0  Female
4  50.0           140.0          NaN    Male
5   NaN           135.0        210.0  Female
6  35.0             NaN        190.0  Female

In mode imputation the missing values are replaced with the most frequently occuring values. It is used when the column comprises of categorical values .It leads to an increse in the majority values of the feature hence leads to an increase in the majority class bias.

In [26]:
print("Before mode imputation")
print(df['Gender'].value_counts(dropna=False))
print("\nAfter mode imputation")
print(df_mode['Gender'].value_counts(dropna=False))

Before mode imputation
Gender
Female    3
Male      2
NaN       2
Name: count, dtype: int64

After mode imputation
Gender
Female    5
Male      2
Name: count, dtype: int64

usin mode imputation we replace the missing value in the categorical column Gender. The missing value is replaced with the majority gender here which is female

In [27]:
#comparison of mean and median imputation
print("Original Dataset Statistics")
display(df.describe())

print("Mean Imputation Statistics")
display(df_mean.describe())

print("Median Imputation Statistics")
display(df_median.describe())

Original Dataset Statistics

             Age  Blood_Pressure  Cholesterol
count   5.000000        5.000000     5.000000
mean   37.000000      130.000000   200.000000
std    10.368221        7.905694    15.811388
min    25.000000      120.000000   180.000000
25%    30.000000      125.000000   190.000000
50%    35.000000      130.000000   200.000000
75%    45.000000      135.000000   210.000000
max    50.000000      140.000000   220.000000

Mean Imputation Statistics

             Age  Blood_Pressure  Cholesterol
count   7.000000        7.000000     7.000000
mean   37.000000      130.000000   200.000000
std     8.465617        6.454972    12.909944
min    25.000000      120.000000   180.000000
25%    32.500000      127.500000   195.000000
50%    37.000000      130.000000   200.000000
75%    41.000000      132.500000   205.000000
max    50.000000      140.000000   220.000000

Median Imputation Statistics

             Age  Blood_Pressure  Cholesterol
count   7.000000        7.000000     7.000000
mean   36.428571      130.000000   200.000000
std     8.521681        6.454972    12.909944
min    25.000000      120.000000   180.000000
25%    32.500000      127.500000   195.000000
50%    35.000000      130.000000   200.000000
75%    40.000000      132.500000   205.000000
max    50.000000      140.000000   220.000000

Mean imputation is used when there is numerical values and no significiant outliers.Median imputation is used when the numerical data contain outliers.Mode imputation is used when the values are categorical in nature. In above datasets which comes under healthcare sector we generally make use of the median imputation because medical values often consists of extreme values.