The objective of this task is to perform end-to-end data preprocessing on the Student
Dataset using Google Colab. This includes dataset exploration, handling missing values, encoding categorical variables, and preparing the dataset for machine learning.
The goal is to ensure the dataset is clean, structured, and ready for model training.

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [ ]:
#Load the CSV file using Pandas
df=pd.read_csv('/content/student_data_100_preprocess.csv')

In [ ]:
#Display:– First 5 rows– Last 5 rows
print("first 5 rows : ")
print(df.head())

first 5 rows :
   Gender   Age  Hours_Studied  Attendance Parental_Education  Final_Score
0    Male   NaN            1.0        65.0           Graduate         95.0
1  Female  21.0            1.0        80.0           Graduate         70.0
2    Male   NaN            3.0        60.0       Postgraduate         60.0
3    Male  21.0            2.0        60.0        High School         80.0
4    Male  20.0            5.0        80.0           Graduate          NaN

In [ ]:
print("last 5 rows : ")
print(df.tail())

last 5 rows :
    Gender   Age  Hours_Studied  Attendance Parental_Education  Final_Score
95  Female  18.0            6.0         NaN       Postgraduate         65.0
96  Female  20.0            6.0        95.0        High School          NaN
97  Female  20.0            3.0        80.0                NaN         75.0
98  Female  18.0            6.0        60.0                NaN         50.0
99    Male  19.0            8.0        90.0                NaN         90.0

In [ ]:
#– Shape of the dataset
print("Shape :")
print(df.shape)

Shape :
(100, 6)

In [ ]:
#– Column names
print("column names:")
print(df.columns.tolist())

column names:
['Gender', 'Age', 'Hours_Studied', 'Attendance', 'Parental_Education', 'Final_Score']

In [ ]:
#– Data types
print("data types:")
print(df.dtypes)

data types:
Gender                 object
Age                   float64
Hours_Studied         float64
Attendance            float64
Parental_Education     object
Final_Score           float64
dtype: object

In [ ]:
#– Numerical columns
num_col = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
print("numerical columns:")
print(num_col)

numerical columns:
['Age', 'Hours_Studied', 'Attendance', 'Final_Score']

In [ ]:
#– Categorical columns
cat_col = df.select_dtypes(include=['object', 'category']).columns.tolist()
print("categorical columns:")
print(cat_col)

categorical columns:
['Gender', 'Parental_Education']

In [ ]:
#statistical summary of numerical columns
print("statistical summary:")
print(df[num_col].describe())

statistical summary:
             Age  Hours_Studied  Attendance  Final_Score
count  91.000000      90.000000   92.000000    93.000000
mean   19.417582       4.366667   76.684783    74.247312
std     1.174412       2.348559   11.843234    14.632198
min    18.000000       1.000000   60.000000    50.000000
25%    18.000000       3.000000   65.000000    60.000000
50%    19.000000       4.000000   77.500000    75.000000
75%    21.000000       6.000000   85.000000    90.000000
max    21.000000       8.000000   95.000000    95.000000

Key statistical measures including mean, standard deviation, minimum, maximum, and quartile values for each numerical column.

In [ ]:
#count missing values per column and Identify which columns contain missing data
df.isnull().sum()

Gender                 0
Age                    9
Hours_Studied         10
Attendance             8
Parental_Education    13
Final_Score            7
dtype: int64

In [ ]:
#– Mean filling
for col in num_col:
    if df[col].isnull().sum() > 0:
        mean_value = df[col].mean()
        df[col].fillna(mean_value, inplace=True)
        print(f"Filled missing values in '{col}' with Mean = {mean_value:.2f}")

Filled missing values in 'Age' with Mean = 19.42
Filled missing values in 'Hours_Studied' with Mean = 4.37
Filled missing values in 'Attendance' with Mean = 76.68
Filled missing values in 'Final_Score' with Mean = 74.25

/tmp/ipykernel_4197/1378400266.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mean_value, inplace=True)

In [ ]:
#– Mode filling
for col in cat_col:
    if df[col].isnull().sum() > 0:
        mode_value = df[col].mode()[0]
        df[col].fillna(mode_value, inplace=True)
        print(f"Filled missing values in '{col}' with Mode = {mode_value}")

Filled missing values in 'Parental_Education' with Mode = Graduate

/tmp/ipykernel_4197/1540618919.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_value, inplace=True)

In [ ]:
#Verify:– No missing values remain
print("missing values :")
print(df.isnull().sum())

missing values :
Gender                0
Age                   0
Hours_Studied         0
Attendance            0
Parental_Education    0
Final_Score           0
dtype: int64

In [ ]:
#confirm changes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Gender              100 non-null    object
 1   Age                 100 non-null    float64
 2   Hours_Studied       100 non-null    float64
 3   Attendance          100 non-null    float64
 4   Parental_Education  100 non-null    object
 5   Final_Score         100 non-null    float64
dtypes: float64(4), object(2)
memory usage: 4.8+ KB

In [ ]:
df.describe()

              Age  Hours_Studied  Attendance  Final_Score
count  100.000000     100.000000  100.000000   100.000000
mean    19.417582       4.366667   76.684783    74.247312
std      1.119758       2.226788   11.354641    14.105415
min     18.000000       1.000000   60.000000    50.000000
25%     18.000000       3.000000   65.000000    65.000000
50%     19.000000       4.000000   76.684783    75.000000
75%     20.250000       6.000000   85.000000    85.000000
max     21.000000       8.000000   95.000000    95.000000

In [ ]:
#Encode Gender using Label Encoding
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])

In [ ]:
#Apply One-Hot Encoding to Parental_Education using Pandas
df = pd.get_dummies(df, columns=['Parental_Education'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Gender                           100 non-null    int64
 1   Age                              100 non-null    float64
 2   Hours_Studied                    100 non-null    float64
 3   Attendance                       100 non-null    float64
 4   Final_Score                      100 non-null    float64
 5   Parental_Education_Graduate      100 non-null    bool
 6   Parental_Education_High School   100 non-null    bool
 7   Parental_Education_Postgraduate  100 non-null    bool
dtypes: bool(3), float64(4), int64(1)
memory usage: 4.3 KB

In [ ]:
#Remove original categorical columns
df.drop('Gender', axis=1, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Age                              100 non-null    float64
 1   Hours_Studied                    100 non-null    float64
 2   Attendance                       100 non-null    float64
 3   Final_Score                      100 non-null    float64
 4   Parental_Education_Graduate      100 non-null    bool
 5   Parental_Education_High School   100 non-null    bool
 6   Parental_Education_Postgraduate  100 non-null    bool
dtypes: bool(3), float64(4)
memory usage: 3.5 KB

In [ ]:
# Separate:– Features (X)– Target (y = Final_Score)
X = df.drop('Final_Score', axis=1)  # Features
y = df['Final_Score']               # Target
print("features shape:", X.shape)
print("target shape:", y.shape)

features shape: (100, 6)
target shape: (100,)

In [ ]:
# Split the dataset:– 80% training and 20% testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In this experiment, the student dataset was successfully preprocessed. The dataset was explored to understand its structure, missing values were identified and handled using appropriate imputation techniques, categorical variables were encoded into numerical formats, and the data was prepared for machine learning by separating features and target variables and performing an 80-20 train-test split. The resulting dataset is clean, consistent, and suitable for predictive modeling tasks.